
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 31 17:35:31 CDT 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Or = 33;
  public static final int Entero = 12;
  public static final int PuntoComa = 25;
  public static final int Coma = 24;
  public static final int IgualIgual = 26;
  public static final int Diferente = 27;
  public static final int Real = 13;
  public static final int Id_Entero = 42;
  public static final int Menor = 31;
  public static final int Repetir = 10;
  public static final int Mayor = 30;
  public static final int Leer = 5;
  public static final int Division = 39;
  public static final int Cadena = 14;
  public static final int Parentesis_c = 22;
  public static final int Falso = 20;
  public static final int Fin = 4;
  public static final int Parentesis_a = 21;
  public static final int Hacer = 18;
  public static final int EOF = 0;
  public static final int DosPuntos = 23;
  public static final int Logico = 15;
  public static final int Not = 34;
  public static final int And = 32;
  public static final int error = 1;
  public static final int Programa = 2;
  public static final int Id_Logico = 43;
  public static final int MenorIgual = 29;
  public static final int Entonces = 17;
  public static final int Variables = 16;
  public static final int Id_Programa = 44;
  public static final int String = 45;
  public static final int Inicio = 3;
  public static final int Si = 7;
  public static final int Resta = 37;
  public static final int Num_Real = 47;
  public static final int MayorIgual = 28;
  public static final int Sino = 8;
  public static final int Escribir = 6;
  public static final int Mientras = 9;
  public static final int Multiplicacion = 38;
  public static final int Verdadero = 19;
  public static final int Numero = 46;
  public static final int Id_String = 40;
  public static final int Hasta = 11;
  public static final int Suma = 36;
  public static final int Igual = 35;
  public static final int Id_Reales = 41;
}

